### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by swastkk** [prabhuignoto/react-chrono#461]
While running 
```bash
npm run dev
```
Getting this error
 ```
⨯ node_modules/react-chrono/dist/react-chrono.esm.js (1:19558) @ window
 ⨯ Internal error: ReferenceError: window is not defined
    at Te (./node_modules/react-chrono/dist/react-chrono.esm.js:1082:5)
    at xo (./node_modules/react-chrono/dist/react-chrono.esm.js:5336:93)
    at ai (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:6505)
    at /home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:11284
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:41727)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at ag (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at ag (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at a_ (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50165)
    at /home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:38901
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:39374)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at a_ (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50165)
    at ak (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49406)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46647)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at a_ (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50165)
    at /home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:38901
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:39374)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at ag (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at ag (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:7923)
    at /home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13014
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:13038)
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:43088)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46298)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at a_ (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:50165)
    at ak (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:49406)
    at e (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:46647)
    at aS (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:48276)
    at ab (/home/swastik/Desktop/tett/prody-frontend/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:41727)
null
```

**Comment by prabhuignoto** [comment]
@swastkk are you running this from a Next JS app or is it a React SPA.

**Comment by swastkk** [comment]
> @swastkk are you running this from a Next JS app or is it a React SPA.

I am working on NextJS

**Comment by prabhuignoto** [comment]
@swastkk have you tried running the app with the (use client)[https://nextjs.org/docs/app/building-your-application/rendering/client-components] directive

**Comment by KarsonJo** [comment]
> @swastkk have you tried running the app with the [use client](https://nextjs.org/docs/app/building-your-application/rendering/client-components) directive

Yes, I tried that and it doesn't work. The reason is that nextjs pre-renders client components on server as well. So even if it's marked as `use client`, `chrono` will still be rendered on server. Maybe putting `window` access into `useEffect` would work?

**Comment by SaiRev0** [comment]
@KarsonJo Hey so did you found any solution ??

**Comment by KarsonJo** [comment]
@SaiRev0 Sorry, I didn't find it, only a workaround.
I tried installing an earlier version (2.4.0) and it seems to not have this problem. But unfortunately this version has the problem of inconsistent random ids generated by client and server. 
Recent releases seem to use more browser APIs, so I ended up wrapping it into a client-only component.

```typescript
// react-chrono-client.ts
"use client"

import type { Chrono as ChronoType } from "react-chrono";
import dynamic from 'next/dynamic'

export const Chrono = dynamic(() => import('react-chrono').then(lib => lib.Chrono), {
  ssr: false,
}) as typeof ChronoType
```

**Comment by Milan-Bhingradiya** [comment]
@KarsonJo  what u did here can u help me to understand ? i want to render chrono component at client side..

**Comment by KarsonJo** [comment]
> @KarsonJo what u did here can u help me to understand ? i want to render chrono component at client side..

@Milan-Bhingradiya `dynamic` with `ssr: false` defines a component that wraps `Chrono` and [turns off server-side rendering](https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading). After that, you need to import `Chrono` from this file (called `react-chrono-client.ts` in this example) instead. Then you can use it as usual without rendering on server.

**Comment by mrbeandev** [comment]
> @SaiRev0 Sorry, I didn't find it, only a workaround. I tried installing an earlier version (2.4.0) and it seems to not have this problem. But unfortunately this version has the problem of inconsistent random ids generated by client and server. Recent releases seem to use more browser APIs, so I ended up wrapping it into a client-only component.
> 
> ```ts
> // react-chrono-client.ts
> "use client"
> 
> import type { Chrono as ChronoType } from "react-chrono";
> import dynamic from 'next/dynamic'
> 
> export const Chrono = dynamic(() => import('react-chrono').then(lib => lib.Chrono), {
>   ssr: false,
> }) as typeof ChronoType
> ```

thanks this worked for me 👍🏻

**Comment by prabhuignoto** [comment]
## ✅ Issue Fixed

Thank you for reporting! All `window` and `navigator` references now have proper SSR guards to prevent "window is not defined" errors.

### What Changed

We've audited the entire codebase and added SSR-safe checks to all browser API calls:

**Example fixes:**

1. **Fullscreen Hook** (`src/hooks/useFullscreen.ts:8`)
```typescript
const userAgent = typeof navigator !== 'undefined' ? navigator.userAgent : '';
const vendor = typeof navigator !== 'undefined' ? navigator.vendor : '';
```

2. **Unique ID Generation (src/utils/index.ts:180)
```
if (typeof window !== 'undefined' && window.crypto?.getRandomValues) {
  // Use crypto API
}
```

3. **Media Queries (src/utils/mediaQueryUtils.ts:11)
```
export function createMediaQuery(query: string): MediaQueryList | null {
  if (typeof window === 'undefined') return null;

  try {
    return window.matchMedia(query);
  } catch (error) {
    console.error('Error creating media query:', error);
    return null;
  }
}
```
If You Still Have Issues
If you're still experiencing "window is not defined" errors:

Check your bundler configuration - Some bundlers need explicit SSR configuration
Use dynamic imports in Next.js:

```
import dynamic from 'next/dynamic';

const Chrono = dynamic(() => import('react-chrono').then(mod => mod.Chrono), {
  ssr: false
});
```

Report the specific line where the error occurs - we may have missed a spot!
Closing as fixed in v3.1.0. Please reopen with specific details if you encounter SSR errors!
